# Generated by Django 3.2.9 on 2022-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='confirm_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='fname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
