# Generated by Django 3.2.9 on 2022-05-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsAPI', '0002_auto_20220507_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='confirm_email',
        ),
    ]
