# Generated by Django 3.2.9 on 2022-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsAPI', '0003_remove_registeruser_confirm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='confirm_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
